#@ load("@ytt:overlay", "overlay")

#@overlay/match by=overlay.subset({"kind": "StatefulSet", "metadata":{"name":"kube-vip-cloud-provider"}}),expects=1
---
spec:
  template:
    spec:
      containers:
      #@overlay/match by="name"
      - name: kube-vip-cloud-provider
        imagePullPolicy: IfNotPresent
